# Generated by Django 3.1.4 on 2020-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
                ('guid', models.CharField(max_length=200, unique=True)),
                ('publish_date', models.DateTimeField(verbose_name='')),
                ('authors', models.ManyToManyField(to='vixra.Author')),
            ],
        ),
    ]
